Broadcasting :
--------------
    The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

In [1]:
import numpy as np

In [2]:
# Creating a NumPy array
arr = np.array([1, 2, 3, 4])

print('-----------------------------------------------')

print(arr)

print('-----------------------------------------------')

print(arr * 2)  # Output: [2 4 6 8]

-----------------------------------------------
[1 2 3 4]
-----------------------------------------------
[2 4 6 8]


In [3]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

# Broadcasting occurs here, aligning arr1 to match arr2's dimensions
result = arr1 + arr2
print(result)

[2 4 6]


In [4]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1], [2], [3]])

print('-----------------------------------------------')
print(arr1)

print(arr2)
print('-----------------------------------------------')

# Broadcasting occurs here, aligning arr1 to match arr2's dimensions
result = arr1 + arr2
print(result)

-----------------------------------------------
[1 2 3]
[[1]
 [2]
 [3]]
-----------------------------------------------
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [5]:
arr = np.array([[1, 2], [3, 4], [5, 6]])

print('-----------------------------------------------')

print(arr)

print('-----------------------------------------------')

print(np.sum(arr, axis=0))  # Sum along columns
print(np.sum(arr, axis=1))  # Sum along rows

-----------------------------------------------
[[1 2]
 [3 4]
 [5 6]]
-----------------------------------------------
[ 9 12]
[ 3  7 11]


Selection
---------
    Let's briefly go over how to use brackets for selection based off of comparison operators.

In [6]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])

print(arr)

[ 10  20  30  40  50  60  70  80  90 100]


In [7]:
arr > 40

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [8]:
bool_arr = arr > 40

print(bool_arr)

[False False False False  True  True  True  True  True  True]


In [9]:
arr[bool_arr]

array([ 50,  60,  70,  80,  90, 100])