What is NumPy?
--------------
1. NumPy stands for Numerical Python.
2. NumPy is a Python library used for working with arrays.
3. It also has functions for working in domain of linear algebra, fourier transform, and matrices.
    
Why Use NumPy?
--------------
1. In Python we have lists that serve the purpose of arrays, but they are slow to process.
2. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
3. The array object in NumPy is called ndarray

Why is NumPy Faster Than Lists?
-------------------------------
1. NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

In [7]:
import numpy

In [11]:
# Convert List to Single Dimention Array

list01 = [10, 20, 30, 40]

print(list01, type(list01))

print('----------------------------------------------------------------------')

numpyList01 = numpy.array(list01)

print(numpyList01, type(numpyList01))


[10, 20, 30, 40] <class 'list'>
----------------------------------------------------------------------
[10 20 30 40] <class 'numpy.ndarray'>


In [12]:
# Convert List to Two Dimention Array

list01 = [[10, 20], [30, 40]]

print(list01, type(list01))

print('----------------------------------------------------------------------')

numpyList01 = numpy.array(list01)

print(numpyList01, type(numpyList01))


[[10, 20], [30, 40]] <class 'list'>
----------------------------------------------------------------------
[[10 20]
 [30 40]] <class 'numpy.ndarray'>


In [13]:
# Convert List to Multi Dimention Array

list01 = [[10, 20], [30, 40], [50, 60]]

print(list01, type(list01))

print('----------------------------------------------------------------------')

numpyList01 = numpy.array(list01)

print(numpyList01, type(numpyList01))

[[10, 20], [30, 40], [50, 60]] <class 'list'>
----------------------------------------------------------------------
[[10 20]
 [30 40]
 [50 60]] <class 'numpy.ndarray'>
