NumPy Operations
----------------
Arithmetic
----------

You can easily perform array with array arithmetic, or scalar with array arithmetic. 

In [1]:
import numpy as np

arr = np.arange(0,10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
arr / arr

C:\Users\Dell 7490\AppData\Local\Temp\ipykernel_21280\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [6]:
arr // arr

C:\Users\Dell 7490\AppData\Local\Temp\ipykernel_21280\376544773.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  arr // arr


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [7]:
arr ** arr

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

Python Numpy Read and Write Text Files
--------------------------------------

In [8]:
x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]], np.int32)

In [9]:
np.savetxt("test.txt", x)

In [10]:
y = np.loadtxt('test.txt')

print(y)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
