What is NumPy?
--------------
1. NumPy stands for Numerical Python.
2. NumPy is a Python library used for working with arrays.
3. It also has functions for working in domain of linear algebra, fourier transform, and matrices.
    
Why Use NumPy?
--------------
1. In Python we have lists that serve the purpose of arrays, but they are slow to process.
2. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
3. The array object in NumPy is called ndarray

Why is NumPy Faster Than Lists?
-------------------------------
1. NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

In [2]:
import numpy

In [4]:
# Convert List to Single Dimention Array

list01 = [10, 20, 30, 40]

print(list01, type(list01))

print('----------------------------------------------------------------------')

numpyList01 = numpy.array(list01)

print(numpyList01, type(numpyList01))


[10, 20, 30, 40] <class 'list'>
----------------------------------------------------------------------
[10 20 30 40] <class 'numpy.ndarray'>


In [5]:
# Convert List to Two Dimention Array

list01 = [[10, 20], [30, 40]]

print(list01, type(list01))

print('----------------------------------------------------------------------')

numpyList01 = numpy.array(list01)

print(numpyList01, type(numpyList01))


[[10, 20], [30, 40]] <class 'list'>
----------------------------------------------------------------------
[[10 20]
 [30 40]] <class 'numpy.ndarray'>


In [13]:
# Convert List to Multi Dimention Array

list01 = [[10, 20], [30, 40], [50, 60]]

print(list01, type(list01))

print('----------------------------------------------------------------------')

numpyList01 = numpy.array(list01)

print(numpyList01, type(numpyList01))

[[10, 20], [30, 40], [50, 60]] <class 'list'>
----------------------------------------------------------------------
[[10 20]
 [30 40]
 [50 60]] <class 'numpy.ndarray'>


Arange :
--------
1. Return evenly spaced values within a given interval.

In [12]:
import numpy as np

In [15]:
a = np.arange(0,10)

print(a, type(a))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [16]:
a = np.arange(1,10)

print(a, type(a))

[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [17]:
a = np.arange(1,10,2)

print(a, type(a))

[1 3 5 7 9] <class 'numpy.ndarray'>


In [18]:
a = np.arange(0,10,2)

print(a, type(a))

[0 2 4 6 8] <class 'numpy.ndarray'>


In [19]:
a = np.arange(10, 0, -1)

print(a, type(a))

[10  9  8  7  6  5  4  3  2  1] <class 'numpy.ndarray'>


Linspace :
----------
1. Return evenly spaced numbers over a specified interval.

In [23]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [24]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [27]:
a = np.linspace(0,50,5, dtype=int,)

print(a)

[ 0 12 25 37 50]


Random :
--------
Numpy also has lots of ways to create random number arrays:

Randint :
---------
Return random integers from low (inclusive) to high (exclusive).

In [30]:
np.random.randint(1,100)

76

In [32]:
a = np.random.randint(1,100,10)

print(a)

[67 28 97  2 77 21 72 47  5  5]


Array Attributes and Methods
----------------------------

In [39]:
arr = np.arange(25)

randarr = np.random.randint(0,50,9)

print(arr)

print('-----------------------------------------------')

print(randarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
-----------------------------------------------
[16 41 27  9 15 31  5  6 12]


01 Reshape :
------------

Returns an array containing the same data with a new shape.

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
randarr.reshape(3, 3)

array([[16, 41, 27],
       [ 9, 15, 31],
       [ 5,  6, 12]], dtype=int32)