Shape:
------
Shape is an attribute that arrays have (not a method):

In [1]:
import numpy

In [2]:
list01 = [[10, 20], [30, 40], [50, 60]]

print(list01, type(list01))

print('----------------------------------------------------------------------')

numpyList01 = numpy.array(list01)

print(numpyList01, type(numpyList01))

[[10, 20], [30, 40], [50, 60]] <class 'list'>
----------------------------------------------------------------------
[[10 20]
 [30 40]
 [50 60]] <class 'numpy.ndarray'>


In [3]:
'''
(3, 2) = (number of rows, number of columns)
'''

numpyList01.shape

(3, 2)

In [6]:
print(numpyList01)

print('----------------------------------------------------------------------')

ex01 = numpyList01.reshape(2, 3)

print(ex01)

[[10 20]
 [30 40]
 [50 60]]
----------------------------------------------------------------------
[[10 20 30]
 [40 50 60]]


max,min,argmax,argmin
---------------------

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [8]:
ranarr = numpy.random.randint(0,50,10)

print(ranarr)

[48 11 14 39 15  7 25 48  5 39]


In [11]:
# To find the Maximum value 

print(ranarr.max())

48


In [12]:
# To find the Minimum value 

minValue = ranarr.min()

print(minValue)

5


In [13]:
# To find the Maximum value position

print(ranarr.argmax())

0


In [14]:
# To find the Minimum value position

print(ranarr.argmin())

8


NumPy Indexing and Selection :
------------------------------

In [29]:
#Creating sample array

arr = numpy.array([10,20,30,40,50,60,70,80,90,100])

print(arr)

[ 10  20  30  40  50  60  70  80  90 100]


In [20]:
#Get a value at an index

print(arr[8])

90


In [21]:
#Get values in a range

arr[1:5]

array([20, 30, 40, 50])

In [30]:
#Setting a value with index range (Broadcasting)

arr[0:5] = 200

#Show
arr

array([200, 200, 200, 200, 200,  60,  70,  80,  90, 100])

Now note the changes also occur in our original array! :
--------------------------------------------------------

In [31]:
print(arr)

[200 200 200 200 200  60  70  80  90 100]


Data is not copied, it's a view of the original array! This avoids memory problems! :
-------------------------------------------------------------------------------------
    In NumPy, when you slice or subset an array, it doesn’t create a new array but instead creates a "view" of the original data. 
    This means that if you modify the view, it will also affect the original array, avoiding extra memory usage.

In [27]:
#To get a copy, need to be explicit

arr_copy = arr.copy()

print(arr_copy)

[200 200 200 200 200  60  70  80  90 100]


In [32]:
arr_copy[2:5] = 250

#Show
arr_copy

array([200, 200, 250, 250, 250,  60,  70,  80,  90, 100])

In [33]:
print(arr)

[200 200 200 200 200  60  70  80  90 100]


Indexing and slicing a multi Dimention array (matrices) :
---------------------------------------------------------
    The general format is arr_2d[row][col] or arr_2d[row,col]. I recommend usually using the comma notation for clarity.

In [35]:
arr_2d = numpy.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [36]:
#Indexing row

arr_2d[1]

array([20, 25, 30])

In [47]:
#Indexing Column

print(arr_2d[0:3,0])

[ 5 20 35]


In [48]:
# Get a Single value

print(arr_2d[0][1])

10
